name = "academy"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.7.0 and < 6.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"
modem = ">= 2.1.3 and < 3.0.0"
rsvp = ">= 2.0.0 and < 3.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[tools.lustre.dev]
proxy = { from = "/academy/api", to = "http://localhost:8800/academy/api" }

[tools.lustre.html]
stylesheets = [{ href = "https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" }]
links = [{ href = "/icon.svg", type = "image/svg+xml", rel = "icon" }]
